image: "python:3.7"

variables:
  WORKON_HOME: .pipenv/venvs
  PIP_CACHE_DIR: .pipenv/pipcache

cache:
  key: pipenv
  paths:
    - .pipenv

on-pull-requests:
  stage: test
  script:
    - pip install pylint
    - pip install pipenv
    - pipenv install
    - pipenv run pip freeze > requirements.txt
    - pipenv run pip freeze
    - pip install -r requirements.txt
    - pylint --fail-under=8 app

except-pull-requests:
  script: echo 'this should not run on pull requests'
  except:
    - external_pull_requests
