image: "python:3.7"

stages:
    - test
    - deploy

variables:
  WORKON_HOME: .pipenv/venvs
  PIP_CACHE_DIR: .pipenv/pipcache

cache:
  key: pipenv
  paths:
    - .pipenv

on-pull-requests:
  stage: test
  script:
    - pip install pylint
    - pip install pipenv
    - pipenv install
    - pipenv run pip freeze > requirements.txt
    - pipenv run pip freeze
    - pip install -r requirements.txt
    - pylint --fail-under=8 -d E0401 -d C0103 app

except-pull-requests:
  script: echo 'this should not run on pull requests'
  except:
    - external_pull_requests
publish:
  only:
    - main
  stage: deploy
  image: 
    name: ubuntu
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - apt-get install python3
    - pip3 install databricks-cli --upgrade
    - echo '{}' > ~/.databricks-connect
    - databricks-cli --version
  script:
    - databricks fs rm  -r dbfs:/datalake/code/search
    - databricks fs mkdirs dbfs:/datalake/code/search
    - databricks fs cp app dbfs:/datalake/code/search -r
